Cargo.toml
src/unix.rs

r? @lfairy 
Rust removed the Android binding for `__errno_location` (see: https://github.com/rust-lang/rust/pull/30175/files#diff-cbcfdc29f0353c1a505c3c1980858a09L17, link courtesy of @alexcrichton). I've verified that this new version links correctly on Android and Android-like platforms (e.g. B2G/gonk/FFOS).
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/lfairy/rust-errno/5)

Fix Android to use _errno, as rustc removed their stub

---

src/windows.rs

Subj.
I don't really see point behind current logic so i propose to simplify it,

Windows: simplify errno description trimming

---

src/lib.rs

This will be helpful with functions taking a raw error `i32` like
`std::io::Error::from_raw_os_error`.

Added Into trait for Error

---

Cargo.toml
src/lib.rs
src/unix.rs

__dfly_error has long been removed from the Rust souce.

Fix errno on DragonFly

---

.travis.yml
Cargo.toml
src/lib.rs
src/wasi.rs

This adds support for errno on the wasm32-wasi target, which is
currently only supported on Rust nightly.
WASI is a new system-call-like API being designed for WebAssembly; see
[the WASI project page](https://github.com/WebAssembly/WASI) for details.

WASI errno support

---

src/unix.rs

Test result on NetBSD.
```console
$ cargo test
Finished dev [unoptimized + debuginfo] target(s) in 0.03s
Running target/debug/deps/errno-92aa8343b3a87dde
running 3 tests
test check_error_into_errno ... ok
test check_description ... ok
test it_works ... ok
test result: ok. 3 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out
Doc-tests errno
running 0 tests
test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out
```

Add NetBSD support

---

src/lib.rs
src/unix.rs

Hi!
I was trying to install `cargo-info` on an illumos machine, and it depends on this library.  With this change, the `errno` crate builds and the tests pass on a recent illumos system:
```
$ cat /etc/release
OpenIndiana Hipster 2020.04 (powered by illumos)
OpenIndiana Project, part of The Illumos Foundation (C) 2010-2020
Use is subject to license terms.
Assembled 03 May 2020
$ uname -a
SunOS newcastle 5.11 rti-master-0-g6682e4c38c i86pc i386 i86pc
$ cargo test
Finished test [unoptimized + debuginfo] target(s) in 0.02s
Running target/debug/deps/errno-f41b053e0159cdd2
running 3 tests
test check_error_into_errno ... ok
test it_works ... ok
test check_description ... ok
test result: ok. 3 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out
Doc-tests errno
running 0 tests
test result: …
```

Add illumos support

---

Cargo.toml
src/hermit.rs
src/lib.rs

Currently, the error handling in RustyHermit [(hermitcore/rusty-hermit)](https://github.com/hermitcore/rusty-hermit) isn't clearly
defined. At the current stage of RustyHermit, only a placeholder
is provided to be compatible to the classical errno interface.

add support of RustyHermit

---

src/lib.rs

To compile below with current (1.47) rustc:
fn f<E: ::std::error::Error>(e: E) {}
fn main() {
f(errnor::Errno(0));
}

Add minimum lines for ::std::error::Error implementation

---

CHANGELOG.md
src/lib.rs
src/unix.rs

this pr adds haiku support
below is a sample excerpt showing a build and test run on a haiku system 
```shell
> uname -a
Haiku shredder 1 hrev55795 Jan 23 2022 07:04:09 x86_64 x86_64 Haiku
> cargo test
Compiling libc v0.2.79
Compiling errno v0.2.8 (/boot/home/src/git/rust-libs/rust-errno)
Finished test [unoptimized + debuginfo] target(s) in 2.33s
Running unittests (target/debug/deps/errno-dcb60f68e1c4165d)
running 4 tests
test check_error_into_errno ... ok
test it_works ... ok
test it_works_with_to_string ... ok
test check_description ... FAILED
failures:
---- check_description stdout ----
thread 'check_description' panicked at 'assertion failed: `(left == right)`
left: `"OS error 1 (strerror_r returned error 1)"`,
right: `"Operation not permitted"`', src/lib.rs:137:5
note: run with …
```

add haiku support

---

.github/workflows/main.yml
CHANGELOG.md
README.md

Rust 1.36 is the earliest version that supports [`Iterator::copied`](https://doc.rust-lang.org/stable/std/iter/struct.Copied.html).
Per https://github.com/lambda-fairy/rust-errno/pull/44#discussion_r870957790, Rust 1.36 should be okay with our biggest dependents `caps` and `rustix`.
Fixes #47

Bump MSRV to 1.36

---

.github/workflows/main.yml
CHANGELOG.md
Cargo.toml
README.md
src/hermit.rs
src/lib.rs
src/unix.rs
src/wasi.rs
src/windows.rs

The first commit is a pure `cargo fmt` run to get a clean slate. The second commit is more interesting and switches from `winapi` to the `windows-sys`, which is maintained by Microsoft.
The wider ecosystem appears to be switching. Let's follow suit so depentents don't have to compile both. At least in my dependency trees `errno` is one of the last holdouts.
This raises the MSRV to 1.48. For the last MSRV bump `caps` and `rustix` were considered. `rustix` already depends on `windows-sys` is interested in having this change while `caps` has since dropped their dependency on `errno` (both per https://github.com/lucab/caps-rs/pull/79).
I have ideas for a few more cleanups/minor fixes but they would collide with these changes, so it would be best to merge this first.

Switch from winapi to windows-sys

---

CHANGELOG.md
Cargo.toml
src/lib.rs
src/unix.rs
src/wasi.rs
src/windows.rs

It was introduced with Rust 1.31 and the current MSRV is 1.48. No need to hold this back any longer.

Switch to Rust 2018 edition

---

Cargo.toml

This field tells cargo about errno's MSRV. It was added with Rust 1.56. Older versions will print a warning about an unknown field if errno is the top-level build job. If errno is merely compiled as a dependency, no warning is printed.
Even though errno's MSRV is currenlty 1.48, it would be good to make this metadata available in a standarized machine-readable format.

Add `rust-version` field

---

src/lib.rs
src/wasi.rs

Recent versions of wasi-libc provide an `__errno_location` function which returns the address of errno, similar to other platforms. Change the errno crate to use that, instead of using the unstable `feature(thread_local)`.
At the moment, only Rust nightly has a new enough wasi-libc to support this, however it's not a regression because the `feature(thread_local)` already dependend on nightly. In the future, the newer wasi-libc will be in stable Rust too, making this work on stable.

wasm32-wasi: Use `__errno_location` instead of `feature(thread_local)`.

---

src/unix.rs

Subject says it all - we we would like to extend support for the ESP IDF framework to this crate as well (it is already supported in Rust STD, `libc`, `rustix`, `socket2` and others.)

Support for the ESP-IDF framework

---

Cargo.toml

This PR bumps the version of `errno-dragonfly`. Even though this dependency is only for `target-os="dragonfly"`, it (and its dependencies) would still get downloaded and type checked on other platforms. This can be problematic since version 0.1.1 specifies `gcc 0.3.0` as a dependency which would cause all dependants to fail when using `-Z minimal-versions` to build (for more info, see [here](https://users.rust-lang.org/t/psa-please-specify-precise-dependency-versions-in-cargo-toml/71277)). Since 0.1.2, they've switched to `cc v1.0` which does build correctly on current versions of rust.
Essentially, this PR unblocks a lot of indirectly dependent crates from using `-Z minimal-versions` once a new release is made, which can have a wide impact on the ecosystem since `rust-errno` is …

Bump errno-dragonfly to remove `gcc` dependency

---

Cargo.toml

Avoid enabling the "std" feature in libc if rust-errno's own "std" feature is not enabled.

Disable "libc/std" in no-std configurations.

---

Cargo.toml
src/unix.rs

DragonFly BSD 5.8+ has __errno_location.
https://github.com/DragonFlyBSD/DragonFlyBSD/commit/60d311380ff2bf02a87700a0f3e6eb53e6034920

Use __errno_location on DragonFly BSD

---

src/unix.rs
src/wasi.rs

We already depend on libc to use strlen, and libc provides strerror_r for all unix/wasi platforms we support.
(As for errno_location, it seems that libc does not provide a corresponding one for some platforms yet.)

Use libc::strerror_r instead of our own definition

---

src/unix.rs

They have the same errno API as iOS.
https://github.com/rust-lang/rust/blob/d1611e39c43e26333ba989cedbd63117be798741/library/std/src/sys/unix/os.rs#L66-L72

Add support for tvOS and watchOS

---

src/unix.rs

Added support for tier 3 [armv7-sony-vita-newlibeabihf](https://doc.rust-lang.org/rustc/platform-support/armv7-sony-vita-newlibeabihf.html) target.
Rust std [actually defines](https://github.com/rust-lang/rust/blob/c5afe0a61e39bdd912803eae8d1887a513bdd172/library/std/src/sys/unix/os.rs#L60C13-L60C34) that by `target_env = "newlib"`, but I am not entirely sure about other newlib targets.
If the goal is to align with std, I can change it to that.

Added support for vita target

---

src/unix.rs
src/wasi.rs

Fixes https://github.com/lambda-fairy/rust-errno/issues/45.
`man 3 strerror_r` says:
The XSI-compliant strerror_r() function returns 0 on success. On error, a (positive) error number is returned (since glibc 2.13), or -1 is returned and errno is set to indicate the error (glibc versions before 2.13).

Fix strerror_r error test

---

src/unix.rs

This is to support the apple vision pro. This target was added in https://github.com/rust-lang/rust/pull/121419 and the `target_os` is `visionos`.

Add visionOS support

---

.github/workflows/main.yml
src/lib.rs
src/unix.rs

This is to support `wasm32-unknown-emscripten` target. 
this change will fix this error:
```
$ cargo test --target wasm32-unknown-emscripten
Compiling errno v0.3.9 (/rust-errno)
error: linking with `emcc` failed: exit status: 1
|
= note: LC_ALL="C" PATH="/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/bin:/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/bin/self-contained:/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/bin:/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/bin/self-contained:/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/bin:/root/.rustup/toolchains/ …
```

Support emscripten

---

CHANGELOG.md
src/lib.rs
src/unix.rs

Hi,
This PR adds support for VxWorks. The test case needed to be modified as the first letter is not capitalized in error strings returned by strerror_r on VxWorks.
Regards,
Kartik.

Add VxWorks support

---

CHANGELOG.md
Cargo.toml
build.rs
src/unix.rs

This PR adds cygwin support, which uses `__errno`.
Blocking:

Add cygwin support
